services:
  jupyter-js:
    image: liuderchi/jupyterlab-ijavascript
    ports:
      - '8888:8888'
    volumes:
      - ./node_modules:/home/node/notebooks/node_modules
    restart: unless-stopped
    working_dir: /home/node/notebooks
    command: jupyter lab --LabApp.token='' --LabApp.password='' --ip=0.0.0.0 --allow-root
